# From https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-identity-access#configure-workload-identity
# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: 944192b6-2d48-4d00-8b9e-b19f60f17afa   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: keyvault-infra-dev        # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: secret1
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: key1
          objectType: key
          objectVersion: ""
    tenantId: c8482830-6d15-4014-a427-155b23c5cdcd                 # The tenant ID of the key vault
