# Deployment for Internal Nginx Ingress Controller to Azure AKS 
# Basic flow from Azure WAF -> AKS Internal Ingress -> SVC/Pods
# Helm version 3
# Nginx Ingress 4.7.2 
# https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
# AKS 1.27.3

helm install nginx-ingress-internal ingress-nginx/ingress-nginx \
    --version 4.7.2 \
    --namespace nginx-internal \
    --set controller.replicaCount=1 \
    --set controller.nodeSelector."kubernetes\.io/os"=linux \
    --set controller.admissionWebhooks.patch.nodeSelector."kubernetes\.io/os"=linux \
    --set controller.admissionWebhooks.patch.image.digest="" \
    --set defaultBackend.nodeSelector."kubernetes\.io/os"=linux \
    --set controller.extraArgs.enable-ssl-passthrough="" \
    --set controller.ingressClassResource.name="internal-nginx" \
    --set controller.ingressClassResource.controllerValue="k8s.io/internal-ingress-nginx" \
    --set controller.service.public="false" \
    --set controller.service.annotations.'service\.beta\.kubernetes\.io/azure-load-balancer-internal'="true" \
    --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"=/healthz \
    --set controller.service.loadBalancerIP="10.180.245.0" \
    --set controller.service.externalTrafficPolicy=Local \
    --set controller.extraArgs.default-ssl-certificate="nginx-public/xxx-tls"
