# https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-identity-access#configure-workload-identity
# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-akv-dev-test-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    
    ## az vmss identity show -g MC_rg-common-test_aks-smartbilling-test_germanywestcentral -n aks-pool1pay-13472262-vmss
    userAssignedIdentityID: 5d87b183-da96-4cf7-8ae4-ad35da957573   # "/subscriptions/93c54646-be8d-459d-9ceb-023cd3cc0282/resourceGroups/MC_rg-common-test_aks-smartbilling-test_germanywestcentral/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-smartbilling-test-keyvault-identity"
    
    keyvaultName: akv-dev-test        # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: es-log-test-smartbilling-username
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty    
        - |
          objectName: es-log-test-smartbilling-password
          objectType: secret             
          objectVersion: ""       
        - |
          objectName: cog-search-test-client-key
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty    
        - |
          objectName: cog-search-test-admin-key
          objectType: secret             
          objectVersion: ""   
          
    tenantId: c8482830-6d15-4014-a427-155b23c5cdcd                 # Itelya
